### ISSUE TITLE
Fix API docs for builder submission endpoint

### ISSUE THREAD

**Issue by ralexstokes** [flashbots/relay-specs#21]
https://github.com/ralexstokes/mev-rs/pull/109#discussion_r1277407859

The example should include the payload and it is currently missing

**Comment by jtraglia** [comment]
Thanks for pointing this out. It's fixed now as of these PRs:

* https://github.com/flashbots/relay-specs/pull/20
* https://github.com/flashbots/relay-specs/pull/22
